name: Hourly check

on:
  workflow_dispatch:
  schedule:
    # Minute zero of every hour
    - cron: '0 * * * *'

env:
  CARGO_TERM_COLOR: always
  IS_BEHIND_NAT: true
  RUST_LOG: info
  IPGEOLOCATIONIO_API_KEY: ${{ secrets.IPGEOLOCATIONIO_API_KEY }}

jobs:
  run-hourly-check:
    runs-on: self-hosted

    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build executable
        run: cargo build

      - name: Ensure IPv4 and IPv6 connectivity
        run: ping -4 -c 4 google.com && ping -6 -c 4 google.com

      - name: Run executable
        run: cargo run

      - name: Create timestamp
        id: create-timestamp
        run: echo "timestamp=$(date --utc)" >> "$GITHUB_OUTPUT"

      - name: Git commit & push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Check ${{ steps.create-timestamp.outputs.timestamp }}
